name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  build-and-test:
    runs-on: selfhosted-ymir

    steps:
      - uses: actions/checkout@v7

      - name: Build ymir
        run: ./build.sh build

      - name: Build test images
        run: ./build.sh build-test-images

      - name: Run tests
        run: ./build.sh test
